### PR TITLE
mdx CodeFile component

### PR DESCRIPTION
**Pull request by onemen**
@kentcdodds,
a few days ago copilot have a [good idea](https://www.youtube.com/watch?v=7eUyQqpmqUs&t=1416s) 

this is first draft of the implementation

I'v added a new rehype plugin `rehypeCodeFile` that transform the new `CodeFile` into regular code block, than `remarkCodeBlocksShiki` do the rest of the work.

CodeFile attributes
 - file: string, required - the file to show in the mdx
 - range: this is the range/ranges of the file to show, when it is not defined , show all content
   i am not sure what will be the best/simple type for this attribute:
   `range={[[2, 4], [10, 20]]}` or `range="2-4,10-20"`
 - hightlight: same as range but specify the line to hightlight.
 - show copy button: boolean
 - show open in playground button: boolean
- show open in problem button: boolean
- show open in solution button: boolean

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Thanks for working on this!

I wonder whether there's a way to benefit from the code block syntax highlighting we've already got in the compiler. Similar to the diff stuff we're doing, instead of a plugin that does the AST transform, we generate markdown which is then passed through the plugin. I think this should be possible. It may be that how to do that is a little interesting though. Like maybe we have a plugin (plugin A) that generates the markdown and then passes that markdown through the existing highlighting plugin (plugin B) we have which then return from plugin A.

Just a thought to reduce the amount of code duplication and feature drift we have.

**Comment by onemen** [comment]
that how i do it here, the new `rehypeCodeFile` run first and replace `CodeFile` node with `pre` then when `remarkCodeBlocksShiki` run it do the rest of the work
```
				options.rehypePlugins = [
					...(options.rehypePlugins ?? []),
					() => rehypeCodeFile(file),
					...rehypePlugins,
				]
```

**Comment by kentcdodds** [comment]
Oh great, I missed that 👍

**Comment by onemen** [comment]
@kentcdodds,

This PR is ready for review

# CodeFile

The `CodeFile` component is used to display code fence(s) from a file mdx file.

## Props

- `file` (required): The path to the file you want to display, relative to the current MDX file. This can be a sibling or subdirectory (e.g.
  `'./app/somefile.jsx'`, `'app/somefile.jsx'`) or in another directory (e.g.
  `'../../somewhere/somefile.jsx'`).
- `range` (optional): The range of lines you want to display from the file. This should be in a format compatible with the [parse-numeric-range](https://www.npmjs.com/package/parse-numeric-range) package.
- `highlight` (optional): The range of lines you want to highlight. This should be in a format compatible with the [parse-numeric-range](https://www.npmjs.com/package/parse-numeric-range) package. every highlight range must be with in range
- `nocopy` (optional): A boolean value that determines whether or not to allow copying of the code. If no value is provided, copying is allowed by default.
- `nonumber` (optional): A boolean value that determines whether or not to display line numbers. If no value is provided, line numbers are displayed by default.
- buttons (optional): A string that determines which buttons to display when the code fence is hovered over. Valid options are 'problem', 'solution', and 'playground'.<br> `OPEN in playground` will be disabled if playground did not set before or if the playground is set to a different app.

## Example

### Input

```jsx
<CodeFile
	file="app/entry.server.tsx"
	range="1-8,10-20"
	highlight="1-2,15-17"
	nocopy
	buttons="problem,solution,playground"
/>
```

This will display lines 1-8 and 10-20 from the file at `app/entry.server.tsx`, with lines 1-2 and 15-17 highlighted. Copying will be disabled, line numbers will be displayed, and the buttons for `'problem'`, `'solution'`, and `'playground'` will be shown.

### Output

range1

### Output - Error

invalid_input

### Output - Warning

if the embedded file changed after you add a code file the README.mdx, a warning will be displayed above the code.

warning

## Code description

- `codefile-mdx.server.ts`: - (new file) export `remarkCodeFile` which is a remark plugin that will replace any `<CodeFile>` node with code fence.`remarkCodeBlocksShiki` handle the rest of the work. All `<CodeFile>` props are validated using `zod` - see `validateProps` and  `createErrorNotification` function.

- `compile-mdx.server.ts`:

  - `remarkCodeFile` plugin was added to bundleMDX remarkPlugins in compileMdx.
  - `getEmbeddedFilesCache` function was added to help handle page refresh when ever embedded file was edit, to reflect the changes in the markdown in view immediately. `kcdshop:file-change` message now includes `embeddedFile: true/false` in its data.

- cache files:

  - name are unique hash from the file path only.
  - `compiledTime`(ms) - added to help determine if recompile is require.
  - `embeddedFiles` data is saved for each `<CodeFile>` in the mdx.
  - new `embeddedFiles.json` file added to `.cache/compile-mdx` the file hold a list off all files that are referenced in `<CodeFile>` (embedded in the  markdown). see `isEmbeddedFile`

- `$exerciseNumber_.$stepNumber.$type.tsx`: `CodeFileNotification` added to handle warning and error messages from compiled `<CodeFile>`

- `update-mdx-cache.tsx`: (new route) - triggered by clicking `Cancel Warning` (see image above), its job is to remove the warning from .json cache file and trigger page update by calling `setModifiedTimesForDir`

- `mdx.tsx`: updated where made to `PreWithCopyToClipboard`, renamed to `PreWithButtons`, to handle `OPEN in App` buttons

## ?

- currently if workshop attendee change any README file, compileMdx will be triggered to update the markdown, I think it should always return the cached content during workshops. (`process.env.NODE_ENV !== 'development'`)
- `kcdLiveReloadConnect` triggered also during workshops, should it turn off?
  same should apply to `kcdshop:file-change` from the serve.
- tests - let me know if you need me to add tests for this. what will be the best approach to test it.

**Review by kentcdodds — APPROVED** [review]
This is unbelievably good. Thank you so much for working on this! I'm seriously blown away at the attention to detail here. I'm definitely going to be using this 💯

**Pull request merged**
