### PR TITLE
fix: add shadow to sticky title

### PR DESCRIPTION
**Pull request by onemen**
Thank you @Ayush-v  for the help

sticky-title

### CODE REVIEW

**Comment by Ayush-v** [comment]
### I have just found another way to do it purely with css 
just need to play with some gradients to get the perfect one
[StackOverflow Solution](https://stackoverflow.com/questions/44793453/how-do-i-add-a-top-and-bottom-shadow-while-scrolling-but-only-when-needed)

```css
.scrollbox {
  overflow: auto;
  width: 200px;
  max-height: 200px;
  margin: 50px auto;
  background: /* Shadow covers */
  linear-gradient(white 30%, rgba(255, 255, 255, 0)), linear-gradient(rgba(255, 255, 255, 0), white 70%) 0 100%, /* Shadows */
  radial-gradient(50% 0, farthest-side, rgba(0, 0, 0, .2), rgba(0, 0, 0, 0)), radial-gradient(50% 100%, farthest-side, rgba(0, 0, 0, .2), rgba(0, 0, 0, 0)) 0 100%;
  background: /* Shadow covers */
  linear-gradient(white 30%, rgba(255, 255, 255, 0)), linear-gradient(rgba(255, 255, 255, 0), white 70%) 0 100%, /* Shadows */
  radial-gradient(farthest-side at 50% 0, rgba(0, 0, 0, .2), rgba(0, 0, 0, 0)), radial-gradient(farthest-side at 50% 100%, rgba(0, 0, 0, .2), rgba(0, 0, 0, 0)) 0 100%;
  background-repeat: no-repeat;
  background-color: white;
  background-size: 100% 40px, 100% 40px, 100% 14px, 100% 14px;
  /* Opera doesn't support this in the shorthand */
  background-attachment: local, local, scroll, scroll;
}
```

just set the 
```css 
background-attachment: local, local, scroll, local; 
```
to attach shadow on top

**Comment by Ayush-v** [comment]
```css
.scrollbox {
	margin: 56px auto auto auto;
	background: /* Shadow covers */ linear-gradient(
			white 30%,
			rgba(255, 255, 255, 0)
		),
		linear-gradient(rgba(255, 255, 255, 0), white 70%) 0 100%,
		/* Shadows */
			radial-gradient(
				50% 0,
				farthest-side,
				rgba(0, 0, 0, 0.2),
				rgba(0, 0, 0, 0)
			),
		radial-gradient(
				50% 100%,
				farthest-side,
				rgba(0, 0, 0, 0.2),
				rgba(0, 0, 0, 0)
			)
			0 100%;
	background: /* Shadow covers */ linear-gradient(
			white 30%,
			rgba(255, 255, 255, 0)
		),
		linear-gradient(rgba(255, 255, 255, 0), white 70%) 0 100%,
		/* Shadows */
			radial-gradient(
				farthest-side at 50% 0,
				rgba(0, 0, 0, 0.2),
				rgba(0, 0, 0, 0)
			),
		radial-gradient(
				farthest-side at 50% 100%,
				rgba(0, 0, 0, 0.2),
				rgba(0, 0, 0, 0)
			)
			0 100%;
	background-repeat: no-repeat;
	background-color: white;
	background-size: 100% 40px, 100% 40px, 100% 14px, 100% 14px;
	/* Opera doesn't support this in the shorthand */
	background-attachment: local, local, scroll, local;
}
```

- just add this to app.css

- and the classname to article tag

working...

**Comment by onemen** [comment]
we don't need `margin: 56px auto auto auto;`

lets see what @kentcdodds  prefers

since we are on react the use effect fells more intuitive

**Comment by onemen** [comment]
shadow-with-css

**Comment by kentcdodds** [comment]
I definitely prefer using pure CSS if it's possible!

**Comment by onemen** [comment]
i can push the css only in a different pr

**Comment by onemen** [comment]
we did it in #19

**Pull request closed without merging**
