### PR TITLE
chore: decode morgan output

### PR DESCRIPTION
**Pull request by onemen**
make the console output more readable

### CODE REVIEW

**Comment by kentcdodds** [comment]
Can you screenshot a before/after?

**Comment by onemen** [comment]
server

**Comment by kentcdodds** [comment]
I don't really see enough of a difference to justify all the extra code 🤔

**Comment by onemen** [comment]
it replace all % char

%2F ---> _
%2B ---> +
%24 ---> $

it looks more readable to me, and `morgan` do the same under the hood just without using `decodeURIComponent`

**Comment by onemen** [comment]
we can do the same with just one extra line

**Review by kentcdodds — APPROVED** [review]
Sure, thanks :)

**Pull request merged**
